-- =============================================================================
-- SleepTrack - Esquema de Base de Datos para Supabase (PostgreSQL en la nube)
-- Archivo: supabase/schema_registros_sueno.sql
-- Módulo: HU1 - Registro de Inicio de Sueño (RF03-RF09, RN01, RN02, RNF04)
-- =============================================================================

-- Habilitar extensión para UUIDs si se requiere a futuro
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- 1. Tabla de Usuarios
-- Prerrequisito para la integridad referencial y clave foránea (RNF04, RF01, RF10).
-- Cumple con el Diagrama de Dominio del Informe #3:
-- Usuario "1" *-- "0..*" RegistroSueno : posee / composicion (eliminación en cascada RF10)
-- =============================================================================
CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    ocupacion VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    meta_sueno NUMERIC(4, 2) DEFAULT 8.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Insertar usuario inicial de desarrollo/pruebas (ID 1 utilizado por defecto en el backend)
INSERT INTO usuarios (id_usuario, nombre, apellido, ocupacion, email, password_hash, meta_sueno)
VALUES (1, 'Usuario', 'Demo', 'Estudiante', 'demo@sleeptrack.app', 'dummy_hash_pbkdf2', 8.0)
ON CONFLICT (id_usuario) DO NOTHING;

-- =============================================================================
-- 2. Tabla de Registros de Sueño (registros_sueno)
-- RF03: Registro diario de hora de acostarse, despertar, fecha y calificación.
-- RF04: Almacena duracion_horas calculada automáticamente cruzando medianoche.
-- RF05 / RN02: Hora de inicio no futura contra reloj en tiempo real.
-- RF06: Tipos de datos estrictos y calificación en escala 1 a 5.
-- RF08 / RN01: Restricción única usuario+fecha para evitar duplicados diarios.
-- RF09: Permite eliminar registros propios.
-- RF10: ON DELETE CASCADE cuando se elimina el usuario propietario.
-- RNF04: Persistencia relacional en la nube garantizada sin almacenamiento local.
-- =============================================================================
CREATE TABLE IF NOT EXISTS registros_sueno (
    id_registro BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    fecha DATE NOT NULL,
    hora_acostarse TIME WITHOUT TIME ZONE NOT NULL,
    hora_despertar TIME WITHOUT TIME ZONE NOT NULL,
    calificacion SMALLINT NOT NULL CHECK (calificacion >= 1 AND calificacion <= 5),
    duracion_horas NUMERIC(4, 2) NOT NULL CHECK (duracion_horas >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),

    -- =========================================================================
    -- REGLA DE NEGOCIO RN01:
    -- "Solo se permite un registro de sueño por usuario por fecha." (RF08)
    -- =========================================================================
    CONSTRAINT uq_registros_sueno_usuario_fecha UNIQUE (id_usuario, fecha)
);

-- =============================================================================
-- 3. Índices de Rendimiento (RNF08)
-- Optimización para consultas frecuentes por usuario y orden cronológico (HU2, RF11-RF13).
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_registros_sueno_usuario_fecha 
    ON registros_sueno(id_usuario, fecha DESC);

CREATE INDEX IF NOT EXISTS idx_registros_sueno_fecha 
    ON registros_sueno(fecha);

-- =============================================================================
-- 4. Trigger para Actualización Automática de updated_at
-- =============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_registros_sueno_updated_at ON registros_sueno;
CREATE TRIGGER trg_registros_sueno_updated_at
    BEFORE UPDATE ON registros_sueno
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- 5. Seguridad a Nivel de Filas (Row Level Security - RLS)
-- Habilita RLS y define políticas de acceso para el cliente del backend.
-- =============================================================================
ALTER TABLE registros_sueno ENABLE ROW LEVEL SECURITY;

-- Política de acceso total para operaciones realizadas por el backend
DROP POLICY IF EXISTS "Permitir acceso completo a registros_sueno" ON registros_sueno;
CREATE POLICY "Permitir acceso completo a registros_sueno"
    ON registros_sueno
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Política para la tabla usuarios
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir acceso completo a usuarios" ON usuarios;
CREATE POLICY "Permitir acceso completo a usuarios"
    ON usuarios
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- =============================================================================
-- 6. Comentarios de Documentación del Esquema
-- =============================================================================
COMMENT ON TABLE registros_sueno IS 'Eventos diarios de descanso ingresados manualmente por los usuarios (HU1, RF03-RF09)';
COMMENT ON COLUMN registros_sueno.id_registro IS 'Identificador primario único del registro';
COMMENT ON COLUMN registros_sueno.id_usuario IS 'Identificador del usuario propietario del registro (FK a usuarios con cascada RF10)';
COMMENT ON COLUMN registros_sueno.fecha IS 'Fecha del evento de descanso (YYYY-MM-DD)';
COMMENT ON COLUMN registros_sueno.hora_acostarse IS 'Hora de inicio de sueño (formato HH:MM:SS, RN02 no futura)';
COMMENT ON COLUMN registros_sueno.hora_despertar IS 'Hora de despertar / fin de descanso';
COMMENT ON COLUMN registros_sueno.calificacion IS 'Autopercepción del descanso en escala del 1 al 5 (RF03, RF05, RF06)';
COMMENT ON COLUMN registros_sueno.duracion_horas IS 'Duración total en horas calculada automáticamente cruzando medianoche (RF04)';
COMMENT ON CONSTRAINT uq_registros_sueno_usuario_fecha ON registros_sueno IS 'RN01: Unicidad estricta de 1 registro por usuario y fecha';
